project_id = "teapriepxqctgjfhposm"

[functions.generate-card-audio]
verify_jwt = true

[functions.telegram-notifications]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.submit-trial-booking]
verify_jwt = false
